### ISSUE TITLE
pg. 477, para.: Azure Virtual Datacenter (VDC) ...

### ISSUE THREAD

**Issue by tmurfet** [benperk/ASA#2]
VDC product is deprecated and replaced by Azure Adoption Framework.
Citation: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/reference/vdc

**Comment by benperk** [comment]
I see the same.  This will be updated with the next version of the book.  It is unlikely to be in the exam, but it is something you would want to know as a Azure Solutions Architect.  Thanks for this and all the other feedback.
