### ISSUE TITLE
pg. 297 "Azure Site Recovery" 

### ISSUE THREAD

**Issue by tmurfet** [benperk/ASA#3]
pg. 297 "Azure Site Recovery" is given as the answer to the question: "What is the best tool for moving an on-premise server or VM to an Azure Virtual Machine?", yet on pg. 347, 1st para. we find: "when you want to move an on-premise workload to an Azure VM, the tool of choice is Azure Migrate." ---seemingly a contradiction.
"So I would say that we should all start looking at ASR as being a disaster-recovery-as-a-service solution, and look at Azure Migrate, as the place to go if you want to migrate anything from anywhere in to Azure." ---> citations: [what is difference between azure migrate and azure site recovery for migration](https://acloud.guru/forums/Migrating-Servers-to-Azure/discussion/-MEoq77yVHJtOjvjf9OB/what%20is%20difference%20between%20azure%20migrate%20and%20azure%20site%20recovery%20for%20migration)
[Azure Site Recovery v Azure Migrate: Server Migration](https://techcommunity.microsoft.com/t5/itops-talk-blog/azure-site-recovery-v-azure-migrate-server-migration/ba-p/997689)

**Comment by benperk** [comment]
The person in the first link you provided nailed it.  The AZ-300 exam would have expected Azure Site Recovery (ASR), while AZ-303 would expect Azure Monitor, in the context of Migration.  Therefore, I will enhance the book, by making it more clear, to reflect the expectations from the AZ-303 exam.  I do cover ASR good in Chapter 1, Chapter 4, Chapter 6 and Chapter 8.  I cover Azure Migrate in Chapter 4 and Chapter 8.  ASR use case is BCDR scenarios and Azure Migrate is for migrating your workloads to Azure.  I remember when I was working with these tools, especially Azure Migrate that I saw a lot of likenesses between ASR and Azure Monitor, it lead me to believe that Azure Monitor depends heavily on some ASR features to perform its duties.   That is an implementation detail, you have the information you need to know to improve exam focused knowledge in the above text.  Thanks for brining this up.  Please continue if you find more and I will respond as quick as possible.
