### ISSUE TITLE
Pg. 527 1st line that reads: "A private key is used to encrypt data."

### ISSUE THREAD

**Issue by tmurfet** [benperk/ASA#5]
Pg. 527 1st line that reads: _A private key is used to encrypt data._ I believe should read: _A public key is used to encrypt data._

**Comment by benperk** [comment]
Yes, thanks for catching this one.  I will get it corrected quickly.  The public key is used to encrypt a message/data and the private key is used to decrypt the message/data.  There are some additional complexities in this area, as I am sure you would agree.  The area of encryption is worthy of its own set of books.
