### ISSUE TITLE
ref. pg. 437 para. : Azure Managed Disk Storage - Incorrect table referenced

### ISSUE THREAD

**Issue by tmurfet** [benperk/ASA#8]
ref. pg. 437 para. Azure Managed Disk Storage: ... Take note again that Azure Managed Disks is deeply integrated with VMSS. Take a look at _Table 4.8_ for their limits and constraints.

Incorrect table referenced, should refer to _Table 4.4_ on pg. 265?

**Comment by benperk** [comment]
Thanks for calling this one out.  The correct reference should be Table 4.4 as you rightly mention, you might also have a look at Table 4.9.  I will get this updated.  The numbers in these tables regarding limits for an Azure product will change over time.  The biggest point I'd like to make is that many people moving workloads to the cloud have expectations that the available capacity is infinite, which isn't that case.  There is massive infrastructure and compute capabilities, don't get me wrong, but there are some constraints, which are greater than the needs of most customers, but there exists constraints none the less.  In some scenarios these limits are present to protect a customer who accidently runs a task which goes rouge, unnecessarily consumes massive resources and resulting an astronomical bill.  These limits are protective to make sure that doesn't happen to Azure customers and, to also make sure there is capacity for all Azure customers as needed...up to the limit.
